## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'genicam'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_genicam'
description = 'Plugin package for the PyMoDAQ framework adding camera compatible with the GeniCam standard to PyMoDAQ'

author = 'Sebastien J. Weber'
author-email = 'sebastien.weber@cnrs.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.1.0', 'harvesters>=1.4.3']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

